### ISSUE TITLE
Error .put('/:id') 

### ISSUE THREAD

**Issue by josemunozr** [Jerolan/node_express__cf_api_bdd#1]
Estoy en el vídeo 11 del curso para crear una API con Nodejs que has impartido.
eh seguido detenidamente cada parte para la creación del CRUD de movie pero al realizar test
del .put('/:id') me arroja el siguiente error:

`Unhandled rejection AssertionError: expected { _id: 1469492458801 } to have a property 'title'`

con node-inspector he logrado realizar un debbug y me he percatado que en routes/movie.js al instanciar la movie, en req.body viene vacio.

`let new_movie = req.body`

en test/movie.js al comentar las expect de tittle y year el test pasa correctamente
`//expect(movie).to.have.property('title', 'pulp fiction')`
` //expect(movie).to.have.property('year', '1993')`

acá mi avance hasta el video número 11. 

https://github.com/josemunozr/api-movie-bdd-nodejs

favor tu ayuda!

**Comment by Jerolan** [comment]
Note en la parte de tu código, en la prueba de movie (test/movie.js) línea 59, no envías la película modificada (debería haber un .send(objt)), debería haber otro objeto, con los mismos índices que movie, llamese new_movie, con los datos alterados, para que haga la actualización

**Comment by josemunozr** [comment]
Tenias razón, efectivamente no estaba realizando un .send(movie).

muchas gracias!!
